# Generated by Django 4.0.4 on 2022-05-03 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archit', models.CharField(max_length=30)),
                ('oeuvre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('creation', models.DateField(blank=True, null=True)),
                ('localisation', models.CharField(max_length=30)),
                ('type_oeuvre', models.TextField(blank=True, null=True)),
                ('architecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archi.architecte')),
            ],
        ),
        migrations.DeleteModel(
            name='Oeuvre',
        ),
    ]
