# Generated by Django 4.0.4 on 2022-05-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archi', '0002_architecte_table_delete_oeuvre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architecte',
            name='oeuvre',
        ),
        migrations.AddField(
            model_name='architecte',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
    ]
