# Generated by Django 4.0.4 on 2022-05-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archi', '0003_remove_architecte_oeuvre_architecte_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecte',
            name='archit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='localisation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='nom',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='type_oeuvre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
