# Generated by Django 4.0.4 on 2022-05-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archi', '0004_alter_architecte_archit_alter_table_localisation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Oeuvre',
        ),
    ]
